-- See /tmp/part1.sql — payload inlined below
-- B1-fix3-prep Part 1: schema delta + UPSERT 70 sub-categories
-- Idempotent. Preserves existing IDs via ON CONFLICT (type, normalized_name).

-- STEP 1: schema delta
ALTER TABLE public.ontology_categories
  ADD COLUMN IF NOT EXISTS keywords                  text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS example_entries           text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS co_occurring_category_ids uuid[] NOT NULL DEFAULT '{}';

CREATE UNIQUE INDEX IF NOT EXISTS ontology_categories_type_name_uk
  ON public.ontology_categories(type, normalized_name);

-- STEP 2: UPSERT 70 sub-categories
INSERT INTO public.ontology_categories
  (type, normalized_name, description, keywords, example_entries, sort_order, status)
VALUES
  ('capability', 'Business & Governance', 'Strategy, compliance, regulatory affairs, programme governance, and export-control management. Capabilities related to running a defence, security, or critical-infrastructure business end-to-end — distinct from building or operating systems.', ARRAY['strategy','compliance','governance','ITAR','EAR','dual-use','EU 2021/821','export control','NSM','security clearance','sikkerhetsklarering','EOS','programme management','BAFO','tender response','contract management','BRREG','GDPR','NIS2'], ARRAY['Strategic advisory','Regulatory compliance','Export control management','Programme governance','Risk & assurance'], 1, 'active'),
  ('capability', 'C4ISR, Communications & PNT', 'Command, control, communications, computers, intelligence, surveillance, reconnaissance, positioning, navigation, and timing — the joint information backbone of modern operations.', ARRAY['C2','C4','C4I','C4ISR','C5ISR','ISR','comms','SATCOM','GNSS','GPS','Galileo','PNT','A-PNT','STANAG 4586','STANAG 5066','tactical data link','Link 16','Link 22','BLOS','beyond-line-of-sight','FMN','federated mission networking'], ARRAY['Command and control','Tactical data links','SATCOM operations','GNSS/INS integration','ISR fusion'], 2, 'active'),
  ('capability', 'Cybersecurity', 'Defensive and offensive cyber operations, secure software development, OT/ICS security, security operations centres, and incident response across IT and operational technology.', ARRAY['cyber','cybersec','infosec','SOC','IR','SIEM','SOAR','zero-trust','OT security','ICS security','IT/OT convergence','ENISA','NIS2','CER directive','MITRE ATT&CK','threat intelligence','cryptography','ISO 27001','NSM grunnprinsipper'], ARRAY['Security operations centre','OT/ICS security','Secure software development','Incident response','Threat intelligence'], 3, 'active'),
  ('capability', 'Electronic Warfare', 'Electromagnetic spectrum operations — electronic support, electronic countermeasures, electronic counter-countermeasures, signals intelligence collection, and spectrum dominance.', ARRAY['EW','ESM','ECM','ECCM','SIGINT','ELINT','COMINT','jamming','spoofing','spectrum dominance','spectrum management','RF deception','electromagnetic battle management','EMBM','low-probability-of-intercept'], ARRAY['Electronic support measures','Electronic countermeasures','Spectrum operations','SIGINT collection','RF deception'], 4, 'active'),
  ('capability', 'Energy & Critical Infrastructure', 'Power generation and distribution, SCADA and industrial control, grid resilience, water utilities, pipeline integrity, subsea cables, and telecom backbones — both military critical infrastructure and civil critical infrastructure within the meaning of NIS2 and CER directive.', ARRAY['grid','SCADA','ICS','OT','NORSOK','NORSOK S-001','NORSOK U-100','NIS2','CER directive','critical infrastructure','kritisk infrastruktur','pipeline','water utility','vannverk','telecom backhaul','subsea cable','kraftforsyning','beredskapsforskriften','DSB'], ARRAY['Grid monitoring','SCADA hardening','Microgrid design','Pipeline integrity','Water utility resilience'], 5, 'active'),
  ('capability', 'Logistics, Supply Chain & Mobility', 'Movement of personnel, materiel, fuel, and equipment; deployable logistics; cold-chain handling; port, airport, and rail operations; host-nation support; strategic and tactical lift.', ARRAY['logistics','supply chain','sustainment','deployable','cold-chain','HNS','host-nation support','port operations','airfield operations','strategic lift','tactical lift','third-party logistics','3PL','ROLE-1 to ROLE-4 logistics support','prepositioning'], ARRAY['Deployable logistics','Fuel & energy supply','Cold-chain logistics','Port and airfield operations','Strategic lift coordination'], 6, 'active'),
  ('capability', 'Manufacturing & Engineering', 'Industrial production capabilities — machining, composites, additive manufacturing, welding, assembly, and qualification testing. The "make it" capability across components and platforms.', ARRAY['manufacturing','machining','composites','additive','AM','3D printing','welding','NDT','non-destructive testing','EN 9100','AS9100','ISO 9001','qualification','certification','production engineering','supply-chain manufacturing','defence industrial base','DIB'], ARRAY['Precision machining','Composite manufacturing','Additive manufacturing','Welding & assembly','NDT inspection'], 7, 'active'),
  ('capability', 'Maritime & Subsea', 'Surface vessel operations, sub-surface and subsea operations, port and harbour activities, offshore infrastructure, and subsea inspection and intervention — covering both naval/coastguard and offshore/oil-and-gas use cases.', ARRAY['maritime','naval','subsea','offshore','ROV','AUV','USV','hydrographic','oseanografi','NORSOK U-100','NORSOK U-101','vessel operations','port security','anti-submarine warfare','ASW','anti-surface warfare','ASuW','mine countermeasures','MCM','Arctic maritime','Svalbard','Barents'], ARRAY['Hydrographic survey','ROV operations','Subsea inspection','Vessel operations','Anti-submarine warfare'], 8, 'active'),
  ('capability', 'Platforms (Air, Land, Sea, Unmanned)', 'Design, integration, and operation of mobility platforms across air, land, sea, and unmanned domains. The "vehicle" side of the capability set, complementing the systems and effectors that ride on those platforms.', ARRAY['platform','airframe','hull','chassis','UAV','UGV','USV','AUV','vessel','vehicle','aircraft','MOTS','COTS','modular platform','dual-use platform','mission modularity','openness','F-35','NH90','P-8'], ARRAY['Fixed-wing aircraft integration','Rotary-wing integration','UAV systems integration','Naval vessel design','Armoured vehicle integration'], 9, 'active'),
  ('capability', 'Preparedness, Response & Medical', 'Civil protection, emergency preparedness, mass-casualty response, field medical and surgical capability, CBRN response, and search and rescue — covering Norwegian DSB "samfunnssikkerhet" remit and NATO RSOM-aligned medical capability.', ARRAY['preparedness','beredskap','samfunnssikkerhet','civil protection','SAR','search and rescue','MCI','mass casualty incident','CBRN response','decontamination','field hospital','ROLE-2','ROLE-3','DSB','Sivilforsvaret','NORTAT','evacuation','crisis communications','Totalforsvar'], ARRAY['Mass-casualty response','Field medical','CBRN decontamination','Search & rescue coordination','Evacuation planning'], 10, 'active'),
  ('capability', 'Sensors & Detection', 'Sensing systems across electro-optical, infrared, radar, sonar, LiDAR, RF, environmental, and CBRN modalities. Both wide-area surveillance and close-range detection use cases.', ARRAY['sensor','radar','sonar','LiDAR','EO','IR','EO/IR','hyperspectral','multispectral','CBRN detection','AIS','environmental monitoring','persistent surveillance','wide-area motion imagery','WAMI','ISR sensor','payload','gimbal'], ARRAY['Radar systems','EO/IR systems','Sonar','LiDAR systems','CBRN detection'], 11, 'active'),
  ('capability', 'Software, Systems & Integration', 'Mission software engineering, systems-of-systems integration, model-based engineering, DevSecOps for defence, and the digital glue that ties sensors, effectors, and command systems together.', ARRAY['software','systems integration','SoS','MBSE','DevSecOps','DevOps','agile','microservices','containers','Kubernetes','data fusion','middleware','API gateway','open architecture','FACE','OMS','UCS'], ARRAY['Mission systems software','Systems-of-systems integration','Model-based engineering','DevSecOps','Data fusion software'], 12, 'active'),
  ('capability', 'Space', 'Launch, satellite operations, ground segment, space situational awareness, earth observation, and SATCOM payload operations. Includes both space-based services and ground-based space-domain capabilities.', ARRAY['space','satellite','SSA','space situational awareness','ground segment','launch','LEO','MEO','GEO','EO satellite','SATCOM','smallsat','cubesat','KSAT','Andøya Space','Telenor Satellite'], ARRAY['Satellite operations','Ground segment','Space situational awareness','Earth observation','SATCOM payloads'], 13, 'active'),
  ('capability', 'Training & Simulation', 'Live, virtual, constructive (LVC) training; synthetic environments; serious-game design; exercise planning; and computer-assisted exercise (CAX) support.', ARRAY['training','simulation','LVC','live virtual constructive','synthetic environment','exercise','CAX','computer-assisted exercise','NATO CAX','JMSC','instructor-led','e-learning','AAR','after-action review'], ARRAY['Live training','Virtual simulation','Constructive simulation','Synthetic training environments','Exercise design'], 14, 'active'),
  ('capability', 'Weapons & Munitions', 'Effectors, munitions, fire-control systems, weapon-system integration, and explosive ordnance disposal — the "kinetic" side of the capability set.', ARRAY['weapon','munition','missile','effector','fire control','EOD','IED','explosive ordnance disposal','propulsion','warhead','ammunition','small arms','artillery','air defence','anti-tank','anti-ship','NAMMO','KONGSBERG'], ARRAY['Missile systems','Small arms','Ordnance disposal (EOD)','Fire control systems','Ammunition'], 15, 'active'),
  ('competence', 'Business & Governance', 'Strategic, programme, and contract management expertise — running defence, security, and critical-infrastructure businesses. Distinct from #15 Regulatory & Compliance, which covers narrower specialist roles in compliance and certification.', ARRAY['strategy','corporate development','programme management','contract management','BAFO','tender writing','partnership management','M&A','framework agreement','DPS-FA','defence procurement','executive leadership','board governance'], ARRAY['Strategic planning expertise','Programme management','Contract & framework management','Partnerships & alliance management','Executive & board governance'], 16, 'active'),
  ('competence', 'C4ISR, Communications & PNT', 'Engineering, integration, and operations expertise in command, control, communications, computers, ISR, positioning, navigation, and timing.', ARRAY['C4I engineer','C4ISR architect','comms engineer','PNT specialist','SATCOM operator','RF engineer','tactical data link specialist','network engineer','signals officer','FMN engineer'], ARRAY['C4ISR systems engineering','Tactical data link engineering','PNT specialist','SATCOM engineering','ISR analyst'], 17, 'active'),
  ('competence', 'Cybersecurity', 'Offensive and defensive cyber expertise, secure-by-design engineering, OT/ICS security, and incident response specialism.', ARRAY['cyber engineer','SOC analyst','incident responder','penetration tester','red teamer','threat hunter','security architect','OT security engineer','cryptographer','IEC 62443 specialist','ENISA practitioner'], ARRAY['Security architecture expertise','Penetration testing','SOC analysis','OT/ICS security engineering','Incident response'], 18, 'active'),
  ('competence', 'Electronic Warfare', 'EW engineering, spectrum analysis, and electromagnetic battle management expertise. Both technical (system design) and operational (employment) specialisms.', ARRAY['EW engineer','EW operator','spectrum analyst','SIGINT analyst','ELINT analyst','COMINT analyst','jamming specialist','RF engineer','EMBM specialist'], ARRAY['EW systems engineering','Spectrum analysis','SIGINT analysis','ELINT analysis','EW operator'], 19, 'active'),
  ('competence', 'Energy & Critical Infrastructure', 'Grid, OT, NORSOK, and critical-infrastructure engineering expertise. Civil engineering specialisms in power, water, telecom, and pipeline infrastructure resilience.', ARRAY['grid engineer','SCADA engineer','OT engineer','NORSOK engineer','NORSOK S-001 specialist','NORSOK U-100 specialist','NIS2 specialist','CER directive specialist','critical infrastructure engineer','kraftverk','nettselskap','vannverk'], ARRAY['Grid engineering expertise','SCADA engineering','Microgrid design','Pipeline engineering','Water utility engineering'], 20, 'active'),
  ('competence', 'Logistics, Supply Chain & Mobility', 'Sustainment, deployable logistics, port and airfield operations, and mobility planning expertise.', ARRAY['logistician','sustainment planner','deployable logistics specialist','cold-chain specialist','HNS planner','port operations specialist','airfield operations specialist','movement controller','materiel manager'], ARRAY['Deployable logistics expertise','Cold-chain logistics','Port operations','Airfield operations','Movement control'], 21, 'active'),
  ('competence', 'Manufacturing & Engineering', 'Machining, composites, additive manufacturing, welding, and qualification engineering expertise.', ARRAY['machinist','composite engineer','additive manufacturing specialist','AM engineer','welding engineer','NDT inspector','production engineer','EN 9100 specialist','qualification engineer','FAI inspector'], ARRAY['Precision machining expertise','Composite engineering','Additive manufacturing engineering','Welding engineering','NDT inspection'], 22, 'active'),
  ('competence', 'Maritime & Subsea', 'Naval architecture, subsea engineering, port operations, and offshore engineering expertise.', ARRAY['naval architect','marine engineer','subsea engineer','ROV pilot','hydrographic surveyor','port operations specialist','Arctic maritime specialist','ice-class engineer','NORSOK U-100 specialist'], ARRAY['Naval architecture','Marine engineering','Subsea engineering','ROV operations expertise','Hydrographic surveying'], 23, 'active'),
  ('competence', 'Platforms', 'Platform-engineering competence across air, land, sea, and unmanned domains. Includes airframe, hull, chassis, and unmanned-platform specialisms.', ARRAY['aerospace engineer','airframe engineer','naval architect (platform)','vehicle engineer','UAV engineer','USV engineer','AUV engineer','payload integration engineer','mission-modularity specialist'], ARRAY['Aerospace engineering','Naval platform engineering','Vehicle engineering','UAV engineering','Payload integration'], 24, 'active'),
  ('competence', 'Preparedness, Response & Medical', 'First-responder, mass-casualty, field-medical, CBRN response, and civil-protection expertise. Norwegian DSB and Sivilforsvaret context included.', ARRAY['first responder','beredskapskoordinator','MCI specialist','ROLE-1','ROLE-2','ROLE-3','field medic','TCCC specialist','CBRN responder','SAR specialist','redningstjeneste','DSB','Sivilforsvaret','Totalforsvar'], ARRAY['Mass-casualty response expertise','Field medical expertise','CBRN response','Search & rescue expertise','Crisis communications'], 25, 'active'),
  ('competence', 'Sensors & Detection', 'Sensor engineering and signal-processing expertise across radar, EO/IR, sonar, LiDAR, RF, and CBRN modalities.', ARRAY['sensor engineer','radar engineer','sonar engineer','EO/IR engineer','LiDAR engineer','signal processing engineer','DSP engineer','payload engineer','CBRN sensor specialist','hyperspectral analyst'], ARRAY['Radar engineering','Sonar engineering','EO/IR engineering','Signal processing','Sensor payload integration'], 26, 'active'),
  ('competence', 'Software, Systems & Integration', 'Software, MBSE, and systems-integration engineering competence. DevSecOps, open architecture, and AI/ML for mission systems are first-class specialisms here.', ARRAY['software engineer','systems engineer','MBSE engineer','SoS architect','DevSecOps engineer','agile coach','microservices architect','data fusion engineer','FACE / OMS / UCS specialist','AI/ML engineer'], ARRAY['Mission software engineering','MBSE engineering','Systems-of-systems architecture','DevSecOps engineering','Data fusion engineering'], 27, 'active'),
  ('competence', 'Space', 'Space-systems engineering, ground-segment operations, and earth-observation expertise. Norwegian context includes Svalbard / Tromsø / Andøya ground-segment specialism.', ARRAY['space systems engineer','satellite engineer','ground segment engineer','SSA analyst','EO satellite engineer','SATCOM payload engineer','smallsat engineer','KSAT operator','Andøya Space specialist'], ARRAY['Space systems engineering','Ground segment engineering','Space situational awareness','EO satellite engineering','SATCOM payload engineering'], 28, 'active'),
  ('competence', 'Training & Simulation', 'Training design, synthetic-environment engineering, instructor competence, and exercise-design specialism.', ARRAY['training designer','instructional designer','simulation engineer','LVC architect','exercise planner','CAX planner','NATO CAX specialist','instructor','AAR specialist'], ARRAY['Training design','Simulation engineering','Synthetic environment engineering','Exercise design','CAX planning'], 29, 'active'),
  ('competence', 'Regulatory & Compliance', 'Specialist competence in defence / dual-use export control, security clearance management, certification, and regulatory compliance. Distinct from #1 Business & Governance (broader strategic / commercial management) — this row captures the narrower specialist roles in export control, classification, certification, and compliance.', ARRAY['export control specialist','ITAR specialist','EAR specialist','EU dual-use 2021/821','end-use certification','NSM clearance','sikkerhetsklarering','kontrollutvalget','NIS2 specialist','CER directive specialist','STANAG conformance','NATO accreditation','ISO 27001 lead auditor','ISO 9001 lead auditor','defence compliance officer'], ARRAY['Export control officer','NSM clearance management','STANAG conformance specialist','NIS2 / CER compliance specialist','Defence compliance officer'], 30, 'active'),
  ('domain', 'Maritime & Coastal Operations', 'Naval, coastguard, port, and coastal operations across surface, sub-surface, and littoral waters. Includes anti-submarine warfare, anti-surface warfare, port security, and coastal surveillance contexts.', ARRAY['maritime','naval','coastguard','kystvakten','port security','harbour security','coastal surveillance','ASW','ASuW','littoral','brown water','blue water','EEZ','exclusive economic zone','Svalbard','Barents','fishery protection'], ARRAY['Coastal surveillance','Port security','Anti-submarine warfare','Maritime domain awareness','Fishery protection'], 31, 'active'),
  ('domain', 'Land Operations', 'Ground manoeuvre, border security, convoy operations, urban operations, and force-protection contexts. Includes both conventional and asymmetric ground-domain operations.', ARRAY['land operations','manoeuvre','ground forces','brigade','battalion','border security','grensevakt','convoy','urban operations','MOUT','force protection','base defence','perimeter security'], ARRAY['Border security','Convoy operations','Urban warfare','Force protection','Base defence'], 32, 'active'),
  ('domain', 'Air Operations', 'Manned and unmanned air operations — air policing, air-to-air refuelling support, BVLOS UAV operations, and counter-UAS. New domain row introduced because the existing 23 single-entry categories had no explicit Air domain.', ARRAY['air operations','air policing','QRA','quick-reaction alert','air-to-air refuelling','AAR','BVLOS','beyond-visual-line-of-sight','UAV operations','counter-UAS','C-UAS','drone defence','airspace control'], ARRAY['Air policing','Air-to-air refuelling support','UAV BVLOS operations','Counter-UAS operations','Airspace control'], 33, 'active'),
  ('domain', 'Space Operations', 'Space-based and space-domain operations — satellite operations, space situational awareness, earth observation, and counter-space contexts.', ARRAY['space operations','space domain awareness','SDA','SSA','satellite operations','earth observation','EO','LEO operations','GEO operations','counter-space','space control','KSAT','Andøya Space','Svalbard'], ARRAY['LEO satellite operations','Space situational awareness','Earth observation','Counter-space operations','Polar ground-segment operations'], 34, 'active'),
  ('domain', 'Cyber & Information Operations', 'Cyber defence, cyber offence, OSINT, information operations, and cognitive warfare contexts. Includes both technical cyber and influence/information operations.', ARRAY['cyber operations','cyber defence','defensive cyber operations','DCO','OCO','offensive cyber','OSINT','open-source intelligence','information operations','InfoOps','psychological operations','PSYOPS','cognitive warfare','disinformation','hybrid threat'], ARRAY['Cyber defence operations','Cyber offensive operations','OSINT collection','Information operations','Hybrid threat response'], 35, 'active'),
  ('domain', 'Surveillance & Reconnaissance (ISR)', 'Intelligence, surveillance, and reconnaissance operations across persistent ISR, maritime domain awareness, and wide-area motion imagery contexts.', ARRAY['ISR','intelligence surveillance reconnaissance','persistent ISR','maritime domain awareness','MDA','WAMI','wide-area motion imagery','surveillance','reconnaissance','multi-INT','all-source intelligence'], ARRAY['Persistent ISR','Maritime domain awareness','Wide-area motion imagery','Multi-INT fusion','Reconnaissance operations'], 36, 'active'),
  ('domain', 'Critical Infrastructure Protection', 'Protection of grid, pipeline, telecom, water, transport, and subsea cable infrastructure under NIS2 / CER directive and Norwegian beredskapsforskriften contexts.', ARRAY['critical infrastructure protection','CIP','kritisk infrastruktur','NIS2','CER directive','beredskapsforskriften','grid protection','pipeline protection','telecom resilience','subsea cable protection','water utility protection','transport sector protection'], ARRAY['Grid protection','Pipeline protection','Telecom resilience','Subsea cable protection','Water utility protection'], 37, 'active'),
  ('domain', 'Civil Protection & Emergency Response', 'Civil protection, mass-casualty response, natural-disaster response, evacuation operations, and search-and-rescue contexts. Norwegian DSB and Sivilforsvaret remit included.', ARRAY['civil protection','samfunnssikkerhet','beredskap','DSB','Sivilforsvaret','mass casualty','MCI','natural disaster','evakuering','evacuation','SAR','search and rescue','redningstjeneste','Totalforsvar','civil emergency'], ARRAY['Mass-casualty response','Natural disaster response','Evacuation operations','SAR (land)','SAR (maritime)'], 38, 'active'),
  ('domain', 'CBRN & Nuclear', 'Chemical, biological, radiological, and nuclear operations — detection, decontamination, nuclear safeguarding, and CBRN incident management contexts.', ARRAY['CBRN','chemical biological radiological nuclear','nuclear safeguarding','IAEA','radiological emergency','kjemisk biologisk','decontamination','CBRN reconnaissance','hazmat','hazmat response'], ARRAY['CBRN detection operations','CBRN decontamination operations','Nuclear safeguarding','Radiological emergency response','Hazmat response'], 39, 'active'),
  ('domain', 'Law Enforcement & Public Safety', 'Police support, counter-terrorism, border control, and public-safety operations. Distinct from civil protection — emphasises policing and enforcement context.', ARRAY['law enforcement','policing','politi','counter-terrorism','CT','anti-terror','border control','grensekontroll','public safety','customs','toll','public order'], ARRAY['Counter-terrorism support','Border control','Police support operations','Public order operations','Customs interdiction'], 40, 'active'),
  ('domain', 'Healthcare & Medical Response', 'Field medical operations, hospital surge, aeromedical evacuation, and military medical operations. Distinct from #8 Civil Protection — focuses on the medical chain itself.', ARRAY['healthcare','medical response','field medical','hospital surge','aeromedical evacuation','MEDEVAC','CASEVAC','ROLE-1','ROLE-2','ROLE-3','ROLE-4','military medicine','trauma response'], ARRAY['Field medical operations','Hospital surge','Aeromedical evacuation','ROLE-2 deployable hospital','Trauma response'], 41, 'active'),
  ('domain', 'Arctic & High North Operations', 'Arctic and High North operational context — Svalbard, Barents, Polar surveillance, cold-weather operations, and Arctic SAR. A Norway-strategic priority domain.', ARRAY['Arctic','High North','nordområdene','Svalbard','Barents','Polar','Polarsirkel','polar code','cold-weather operations','Arctic SAR','Arctic surveillance','Arctic logistics','JRCC Bodø'], ARRAY['Arctic surveillance','Arctic SAR','High North logistics','Cold-weather operations','Svalbard support operations'], 42, 'active'),
  ('product_type', 'Sensors (EO/IR & LiDAR)', 'Electro-optical, infrared, multispectral, hyperspectral, and LiDAR sensors — both standalone systems and stabilised payloads for manned and unmanned platforms.', ARRAY['EO','IR','EO/IR','electro-optical','infrared','thermal','LiDAR','multispectral','hyperspectral','MWIR','LWIR','SWIR','gimbal','stabilised payload','FLIR','daylight camera','image intensifier','NVD'], ARRAY['Camera system (EO/IR)','LiDAR system','Thermal imager','Multispectral camera','Gimballed payload'], 43, 'active'),
  ('product_type', 'Sensors (RF, Radar & SIGINT)', 'RF, radar, and SIGINT/ELINT/ESM/ECM hardware — coastal surveillance radars, counter-UAS radars, phased-array radars, SIGINT receivers, and spectrum analysers.', ARRAY['radar','RF','SIGINT','ELINT','COMINT','ESM','ECM','phased array','AESA','coastal radar','counter-UAS radar','surveillance radar','fire-control radar','air-defence radar','spectrum analyser','RWR','radar warning receiver'], ARRAY['Radar system','Antenna system','Spectrum analyser','SIGINT receiver','Counter-UAS radar'], 44, 'active'),
  ('product_type', 'Sensors (Acoustic & Sonar)', 'Acoustic and sonar sensors across hull-mounted, towed-array, dipping, side-scan, and multi-beam configurations — for ASW, MCM, and hydrographic / subsea inspection use.', ARRAY['sonar','acoustic','hull-mounted sonar','HMS','towed array','dipping sonar','side-scan sonar','multi-beam echo sounder','MBES','sub-bottom profiler','hydrophone','sonobuoy','ASW','MCM'], ARRAY['Sonar','Hull-mounted sonar','Towed array sonar','Multi-beam echo sounder','Sonobuoy'], 45, 'active'),
  ('product_type', 'Unmanned Air Platforms', 'Fixed-wing, rotary, hybrid, and tethered unmanned air platforms across micro, mini, tactical, MALE, and HALE classes — including loitering munitions.', ARRAY['UAV','UAS','unmanned aerial vehicle','unmanned aerial system','drone','fixed-wing UAV','rotary UAV','multirotor','tactical UAV','MALE','HALE','loitering munition','tethered UAV','group 1','group 2','group 3'], ARRAY['UAV (fixed-wing)','UAV (rotary)','Tactical UAV','MALE UAV','Loitering munition'], 46, 'active'),
  ('product_type', 'Unmanned Surface & Subsea Platforms', 'Unmanned surface vessels (USV), autonomous underwater vehicles (AUV), and remotely operated vehicles (ROV) — across military, hydrographic, and offshore use.', ARRAY['USV','AUV','ROV','unmanned surface vessel','autonomous underwater vehicle','remotely operated vehicle','mine-hunting USV','survey AUV','inspection ROV','work-class ROV','observation-class ROV'], ARRAY['USV','AUV','ROV','Mine-hunting USV','Survey AUV'], 47, 'active'),
  ('product_type', 'Manned Platforms (Vessels, Vehicles, Aircraft)', 'Manned platforms — naval vessels, ground vehicles, fixed-wing aircraft, and rotary aircraft used in defence, coastguard, and critical-infrastructure operations.', ARRAY['vessel','ship','naval vessel','patrol vessel','coastal interceptor','frigate','corvette','armoured vehicle','AFV','IFV','MRAP','helicopter','fixed-wing aircraft','maritime patrol aircraft','MPA','transport aircraft'], ARRAY['Vessel','Patrol vessel','Armoured vehicle','Helicopter','Maritime patrol aircraft'], 48, 'active'),
  ('product_type', 'Communications & Networking', 'Tactical, strategic, and satellite communications products — radios, data links, SATCOM terminals, AIS, mesh networking, and tactical routing.', ARRAY['radio','tactical radio','VHF','UHF','HF','comms radio','data link','Link 16','Link 22','SATCOM','satcom terminal','AIS','mesh radio','BLOS terminal','tactical router','FMN node'], ARRAY['Communication radio','Data link','SATCOM terminal','AIS system','Tactical radio'], 49, 'active'),
  ('product_type', 'C4 & Mission Software', 'Mission software products — command and control, sensor fusion, mission planning, simulation, integration platforms, and common operating picture systems.', ARRAY['C2','command and control','mission planning','sensor fusion','common operating picture','COP','data fusion platform','integration platform','simulation platform','mission system','decision support'], ARRAY['C2 software','Data fusion platform','Integration platform','Simulation platform','Common operating picture'], 50, 'active'),
  ('product_type', 'Navigation & PNT Systems', 'Navigation systems across GNSS, INS, alternate PNT, maritime navigation, and underwater positioning.', ARRAY['navigation','PNT','A-PNT','GNSS','GPS','Galileo','GLONASS','BeiDou','INS','inertial navigation','dead reckoning','eLoran','anti-jam GNSS','M-code','maritime navigation','buoy','underwater positioning','USBL','LBL'], ARRAY['Navigation system (GNSS/INS)','Anti-jam GNSS','INS-only navigation system','Maritime navigation aid','Underwater positioning system'], 51, 'active'),
  ('product_type', 'Electronic Warfare & Cryptographic Systems', 'EW effectors, cryptographic devices, and information-security hardware. Includes jammers, deception systems, HAIPE encryptors, and tactical crypto modules.', ARRAY['EW system','jammer','RF jammer','GNSS jammer','counter-IED jammer','RF deception','encryption device','crypto module','HAIPE','type-1 crypto','COMSEC','TRANSEC','EMSEC'], ARRAY['Jammer','Encryption device','HAIPE encryptor','Counter-IED jammer','Tactical jammer'], 52, 'active'),
  ('product_type', 'Weapons, Munitions & Effectors', 'Weapon systems, munitions, missiles, ammunition, and effectors across air, land, sea, and counter-UAS use.', ARRAY['weapon','missile','anti-ship missile','anti-air missile','air-defence missile','anti-tank missile','anti-tank guided weapon','ATGW','MANPADS','small arms','mortar','artillery','ammunition','loitering effector','counter-UAS effector','NAMMO','KONGSBERG'], ARRAY['Missile / effector system','Anti-ship missile','Air-defence missile','Small-arms ammunition','Loitering effector'], 53, 'active'),
  ('product_type', 'Power & Energy Systems', 'Battery, fuel-cell, microgrid, generator, and hybrid power systems for tactical, deployable, and forward-base power.', ARRAY['battery','energy storage','fuel cell','microgrid','generator','genset','hybrid power','solar / wind hybrid','tactical battery','deployable power','forward-base power','off-grid'], ARRAY['Battery / energy storage','Fuel cell / microgrid','Generator / power supply','Hybrid genset','Deployable microgrid'], 54, 'active'),
  ('product_type', 'CBRN, Medical & Life Support Systems', 'CBRN detection and decontamination equipment, field medical systems, water purification, and personal life-support equipment.', ARRAY['CBRN detector','chemical detector','biological detector','radiological detector','decontamination','decon','field hospital','ROLE-2 hospital','ROLE-3 hospital','water purification','life support','PPE','personal protective ensemble','mask','respirator'], ARRAY['Decontamination system','Field hospital / medical unit','Water purification system','CBRN detector','Personal protective ensemble'], 55, 'active'),
  ('product_type', 'Personal & Field Equipment', 'Soldier-borne and team-level field equipment — body armour, helmets, load-bearing equipment, shelters, and tactical clothing.', ARRAY['body armour','ballistic vest','plate carrier','tactical helmet','ballistic helmet','load-bearing equipment','LBE','MOLLE','tactical pack','shelter','modular shelter','tent system','soldier system','dismounted soldier'], ARRAY['Body armour / protective equipment','Shelter / temporary structure','Tactical helmet','Load-bearing equipment','Modular shelter system'], 56, 'active'),
  ('product_type', 'Components & Sub-Assemblies', 'Components and sub-assemblies that go into larger systems — circuit boards, composite components, machined parts, optical assemblies, power electronics, cable assemblies.', ARRAY['PCB','circuit board','FPGA','composite component','machined component','optical assembly','cable assembly','power electronics','antenna element','sub-assembly','COTS component','MIL-STD component'], ARRAY['PCB / circuit board','Composite component','Machined component (metal)','Cable assembly','Optical assembly'], 57, 'active'),
  ('service_type', 'Advisory & Consulting', 'Advisory and consulting services — strategy advisory, programme advisory, acquisition advisory, risk assessment, security advisory, EW assessment, and tender support.', ARRAY['advisory','consulting','strategy advisory','programme advisory','acquisition advisory','tender support','BAFO support','security advisory','EW assessment','risk assessment','gap analysis','due diligence'], ARRAY['Programme advisory','Tender support','Acquisition advisory','Risk assessment','Security advisory'], 58, 'active'),
  ('service_type', 'Design & Engineering Services', 'Engineering design services — system architecture, naval architecture, network design, secure design, cyber-physical design, HMI/UX, and platform / vessel design.', ARRAY['design','engineering services','system architecture','naval architecture','network design','secure network design','cyber-physical design','HMI design','UX design','vessel design','MBSE'], ARRAY['System architecture','Naval architecture','Secure network design','Cyber-physical design','Vessel design'], 59, 'active'),
  ('service_type', 'Systems Integration & Installation', 'Systems integration and installation services — mission-system integration, sensor integration, comms integration, vessel and vehicle installation.', ARRAY['systems integration','integration','installation','mission system integration','sensor integration','comms integration','vessel installation','vehicle installation','commissioning','factory acceptance testing','FAT','site acceptance testing','SAT'], ARRAY['Mission-system integration','Sensor integration','Comms integration','Vessel installation','FAT / SAT support'], 60, 'active'),
  ('service_type', 'Testing, Validation & Certification', 'Testing, validation, certification, and calibration services — type approval, environmental testing, STANAG conformance, EMC / EMI, and calibration.', ARRAY['testing','validation','verification','V&V','type approval','environmental testing','MIL-STD-810','EMC','EMI','STANAG conformance','STANAG 4586 conformance','calibration','certification','qualification testing'], ARRAY['Type approval testing','Environmental testing','STANAG conformance test','Calibration','EMC / EMI testing'], 61, 'active'),
  ('service_type', 'Inspection & Survey', 'Inspection and survey services — subsea inspection, structural NDT, hydrographic survey, pipeline inspection, and aerial / aerial-drone survey.', ARRAY['inspection','survey','subsea inspection','NDT','non-destructive testing','hydrographic survey','pipeline inspection','structural inspection','aerial survey','drone survey','photogrammetry'], ARRAY['Subsea inspection','Structural NDT','Hydrographic survey','Pipeline inspection','Aerial survey'], 62, 'active'),
  ('service_type', 'Maintenance, Repair & Overhaul', 'MRO services across airframes, vessels, vehicles, sensors, and field-level maintenance. Covers depot-level and field-level activity.', ARRAY['MRO','maintenance','repair','overhaul','depot maintenance','field maintenance','airframe MRO','vessel MRO','vehicle MRO','sensor MRO','level 1 / 2 / 3 / 4 maintenance','scheduled maintenance','unscheduled maintenance'], ARRAY['Airframe MRO','Vessel MRO','Vehicle MRO','Sensor MRO','Field-level maintenance'], 63, 'active'),
  ('service_type', 'Operations & Platform Services', 'Operations-as-a-service — UAV operations, vessel operations, crew leasing, fleet management, and platform operations on behalf of customer.', ARRAY['operations','platform operations','UAV operations as-a-service','vessel operations','crew leasing','fleet management','ISR-as-a-service','surveillance services','contractor-operated'], ARRAY['UAV operations as-a-service','Vessel operations','Crew leasing','Fleet management','Surveillance-as-a-service'], 64, 'active'),
  ('service_type', 'Logistics & Transport', 'Logistics and transport services — strategic lift, hazardous-cargo transport, cold-chain transport, port and airport handling.', ARRAY['logistics services','transport','strategic lift','hazardous cargo','hazmat transport','cold-chain transport','port handling','airport handling','freight forwarding','customs clearance'], ARRAY['Strategic lift','Hazardous-cargo transport','Cold-chain transport','Port handling','Airport handling'], 65, 'active'),
  ('service_type', 'Emergency & Crisis Response', 'Emergency response services — oil-spill response, mass-casualty response, CBRN decontamination, evacuation operations, and crisis response.', ARRAY['emergency response','crisis response','oil spill response','OPRC','mass casualty response','CBRN decontamination','evacuation services','hazmat response','IMO OPRC','response on call'], ARRAY['Oil-spill response','Mass-casualty response','CBRN decontamination','Evacuation operations','Hazmat response'], 66, 'active'),
  ('service_type', 'Medical & Health Services', 'Field medical, aeromedical evacuation, telemedicine, and contracted medical services.', ARRAY['medical services','field medical','aeromedical evacuation','telemedicine','contracted medical','ROLE-2 service','hospital surge service','medical staffing'], ARRAY['Field medical services','Aeromedical evacuation','Telemedicine','Contracted ROLE-2 service','Medical staffing'], 67, 'active'),
  ('service_type', 'Training & Exercise Services', 'Training and exercise services — operator training, maintainer training, exercise design, red-teaming, computer-assisted exercise support.', ARRAY['training service','operator training','maintainer training','instructor service','exercise design','red team','red-teaming','CAX support','NATO CAX','exercise control','AAR support'], ARRAY['Operator training','Maintainer training','Exercise design','Red-teaming','CAX support'], 68, 'active'),
  ('service_type', 'Project & Programme Management', 'Project and programme management services — programme management office, schedule management, earned-value management, risk management.', ARRAY['project management','programme management','PMO','programme management office','schedule management','earned value management','EVM','risk management','change management'], ARRAY['Programme management office','Schedule management','Earned-value management','Risk management','Change management'], 69, 'active'),
  ('service_type', 'Cyber & Information Security Services', 'Cyber and information-security services — penetration testing, vulnerability assessment, SOC-as-a-service, spectrum management, incident response retainer.', ARRAY['cyber services','penetration testing','pentest','vulnerability assessment','SOC-as-a-service','MSSP','managed security service','incident response retainer','spectrum management','spectrum monitoring'], ARRAY['Penetration testing','Vulnerability assessment','SOC-as-a-service','Spectrum monitoring','Incident-response retainer'], 70, 'active')
ON CONFLICT (type, normalized_name) DO UPDATE
  SET description     = EXCLUDED.description,
      keywords        = EXCLUDED.keywords,
      example_entries = EXCLUDED.example_entries,
      updated_at      = now();

-- Post-check: 15 capability rows present (sample of 70)
DO $post$
DECLARE v_missing int;
BEGIN
  WITH expected(type, normalized_name) AS (
    SELECT type, normalized_name FROM (VALUES
      ('capability','Business & Governance'),('capability','C4ISR, Communications & PNT'),
      ('capability','Cybersecurity'),('capability','Electronic Warfare'),
      ('capability','Energy & Critical Infrastructure'),('capability','Logistics, Supply Chain & Mobility'),
      ('capability','Manufacturing & Engineering'),('capability','Maritime & Subsea'),
      ('capability','Platforms (Air, Land, Sea, Unmanned)'),('capability','Preparedness, Response & Medical'),
      ('capability','Sensors & Detection'),('capability','Software, Systems & Integration'),
      ('capability','Space'),('capability','Training & Simulation'),('capability','Weapons & Munitions')
    ) AS t(type, normalized_name)
  )
  SELECT count(*) INTO v_missing FROM expected e
  LEFT JOIN public.ontology_categories oc
    ON oc.type = e.type AND oc.normalized_name = e.normalized_name
  WHERE oc.id IS NULL;
  IF v_missing > 0 THEN
    RAISE EXCEPTION 'Part 1 post-check FAIL: % expected capability rows missing', v_missing;
  END IF;
END $post$;